import base64
import io
import json
import logging
import boto3
from PIL import Image
from botocore.exceptions import ClientError
import random

class ImageError(Exception):
    "Custom exception for errors returned by Amazon Titan Image Generator G1"

    def __init__(self, message):
        self.message = message

logger = logging.getLogger(__name__)
logging.basicConfig(level=logging.INFO)

def generate_image(model_id, body):
    
    """
    Generate an image using Amazon Titan Image Generator G1 model on demand.
    Args:
        model_id (str): The model ID to use.
        body (str) : The request body to use.
    Returns:
        image_bytes (bytes): The image generated by the model.
    """
    logger.info("Generating image with Amazon Titan Image Generator G1 model %s", model_id)
    
    # Ensure that the correct region is set
    bedrock = boto3.client(service_name='bedrock-runtime', region_name='us-east-1')

    accept = "application/json"
    content_type = "application/json"

    try:
        response = bedrock.invoke_model(
            body=body,
            modelId=model_id,
            accept=accept,
            contentType=content_type
        )

        response_body = json.loads(response.get("body").read())

        base64_image = response_body.get("images")[0]
        base64_bytes = base64_image.encode('ascii')
        image_bytes = base64.b64decode(base64_bytes)

        finish_reason = response_body.get("error")

        if finish_reason is not None:
            raise ImageError(f"Image generation error. Error is {finish_reason}")

        logger.info("Successfully generated image with Amazon Titan Image Generator G1 model %s", model_id)
        return image_bytes

    except ClientError as err:
        message = err.response["Error"]["Message"]
        logger.error("A client error occurred: %s", message)
        raise

def main():
    logging.basicConfig(level=logging.INFO, format="%(levelname)s: %(message)s")

    model_id = 'amazon.titan-image-generator-v2:0'
    
    prompt = """
    A person dedicatedly working on their {future_dream}.
    a background that matches their {future_dream},
    detaily background.
    Looking at viewer.
    Finely Detailed eyes and face.
    High nose bridge.
    Allowing the background to be an important element of the composition.
    Draw a white person or a yellow person.
    A Whole Face.
    """

    future_dream = ""  # 원하는 미래 직업을 여기에 입력합니다.

    # Random seed generation
    random_seed = random.randint(0, 214783647)
    
    body = json.dumps({
        "taskType": "TEXT_IMAGE",
        "textToImageParams": {
            "text": prompt.format(future_dream=future_dream)
        },
        "imageGenerationConfig": {
            "numberOfImages": 1,
            "height": 1024,
            "width": 1024,
            "cfgScale": 9.0,
            "seed": random_seed  # Random seed is used here
        }
    })

    try:
        image_bytes = generate_image(model_id=model_id, body=body)
        image = Image.open(io.BytesIO(image_bytes))

        # Save the generated image to a file named 'result.jpg'
        image.save('result.jpg', format='JPEG')
        logger.info("Image saved as result.jpg")

        # Optionally display the image as well
        image.show()
        
    except ClientError as err:
        print(f"A client error occurred: {err}")
    except ImageError as err:
        logger.error(err.message)
        print(err.message)
    else:
        print(f"Finished generating image with Amazon Titan Image Generator G1 model {model_id}.")

if __name__ == "__main__":
    main()
